version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "forwarder-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w8dj7btx59k2"
s3_prefix = "forwarder-backend"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
