AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ForwarderEmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: src/
      Handler: main.lambda_handler
      Runtime: python3.9
      Policies:
        - SESCrudPolicy:
            IdentityName: '*'
      FunctionUrlConfig:
        AuthType: NONE
      

Outputs:
  MyFunctionUrlEndpoint:
      Description: "Email Sender Lambda Function URL Endpoint"
      Value:
        Fn::GetAtt: ForwarderEmailSenderFunctionUrl.FunctionUrl